# Generated by Django 5.2.14 on 2026-05-21 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(choices=[('bus', 'Автобус'), ('electrobus', 'Электробус'), ('tram', 'Трамвай')], max_length=50)),
                ('start_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Наличными'), ('transfer', 'Перевод по номеру телефона')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('studying', 'Идет обучение'), ('completed', 'Обучение завершено')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
